# Generated by Django 5.1.1 on 2024-11-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('unpaid', 'Не оплачен')], default='unpaid', max_length=6, verbose_name='Статус оплаты'),
        ),
    ]
